
# User.destroy_all
# Item.destroy_all
#user seeds
u1 = User.create!(username: "Bob", first_name: "bob", last_name: "bobby", email: "bob@bob.com", password: "password", password_confirmation: "password")
u2 = User.create!(username: "Aaa",first_name: "Aaa", last_name: "zzz", email: "aaa@aaa.com", password: "password", password_confirmation: "password")
u3 = User.create!(username: "Imran", first_name: "Imran", last_name: "imran", email: "imran@imran.com", password: "password", password_confirmation: "password")

i1 = Item.create!(name: "Omega Seamaster", description: "The Omega Seamaster is a line of automatic winding chronometer and quartz watches that Omega has produced since 1948. The Seamaster is particularly popular among celebrities, with famous wearers including Prince William, Joe Biden, Jeremy Clarkson, Gabriel Holmes and Adam Savage. An Omega Seamaster typically has a stainless steel case and bracelet (Bond style with Omega symbol clasp), screw-in crown and case-back, engraved with the Omega hippocampus logo, up to 1200-metre water resistant, luminescent hands, unidirectional bezel, blue, silver or black dial with orange accents, sapphire crystal (anti-reflective) and helium release valve.", value: 1200, image: "http://www.bluemaize.net/im/watches/used-omega-watches-10.jpg", user_id: u1.id)

i2 = Item.create!(name: "Omega Speedmaster", description: "Omega Speedmaster is a line of chronograph wristwatches produced by Omega SA. While chronographs have been around since the late 1800s, Omega first introduced this line of chronographs in 1957. Since then, many different chronograph movements have been marketed under the Speedmaster name. The manual winding Speedmaster Professional or Moonwatch is the best-known and longest-produced; it was worn during the first American spacewalk as part of NASA's Gemini 4 mission and was the first watch worn by an astronaut walking on the Moon during the Apollo 11 mission. The Speedmaster Professional remains one of several watches qualified by NASA for spaceflight and is still the only one so qualified for EVA.[3] The Speedmaster line also includes other models, including analog-digital and automatic mechanical watches", value: 1800, image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Vintage_Omega_Speedmaster_%22Pre-moon%22.jpg/1024px-Vintage_Omega_Speedmaster_%22Pre-moon%22.jpg", user_id: u1.id)

i3 = Item.create!(name: "Rolex DateJust", description: "The original Datejust model REF: 4467 was only available in 18 karat gold and had a small bubble back winder with a deeply domed back. It also featured a waterproof Oyster case, a fluted bezel, and a signature Jubilee bracelet, making it instantly identifiable as a Rolex. Rolex cyclops lens Closeup Look
Over the years, the Datejust movement went through subtle improvements to its features while remaining true to its original design. Several years after its debut, In 1954, Rolex added the now famous “Cyclops Lens” as a major update.The Datejust is offered with two classic Rolex bracelets: the jubilee and the oyster. The original Datejust was launched with a case size of 36mm. Later, however, ladies' and mid-sized versions became available. The Turn-o-Graph model was introduced in 1955 as an award given to US Air Force pilots returning from combat missions. It featured a rotating bezel marked to 60 minutes, which can be used to measure time intervals. Datejusts of this type have been nicknamed Thunderbirds. Chuck Yeager wore one of these models when he broke the sound barrier.[1] This would be the basis for the Rolex Explorer (designed for Sir Edmund Hillary's Mount Everest expedition), the Rolex Submariner, and the Rolex Sea Dweller.", value: 1900, image: "http://cdn.chrono24.com/images/uhren/images_13/s6/2695613_xxl.jpg?v=4", user_id: u2.id)

i4 = Item.create!(name: "Navitimer", description: "The favorite watch of pilots and dedicated aeronautical enthusiasts since 1952, the Navitimer 01 combines a technical and original design with Manufacture Breitling Caliber 01 – a true mark of reliability and performance. This legendary model is distinguished by its steel case and its black dial with a red seconds hands, silver chronograph counters and applied hour-markers or numerals. It is also available in a red gold version with other dial colors. Its bidirectional ratcheted rotating bezel ensures smooth and easy handling of the famous circular aviation slide rule.", value: 10, image: "https://www.breitling.com/media/image/0/base/asset-version-bf55c8bd66/ab012012-bb01-435x-a20ba1.jpg", user_id: u3.id)

i5 = Item.create!(name: "Heuer Monaco", description: "The Heuer Monaco is a series of automatic chronograph wristwatch originally introduced by Heuer in 1969 in honour of the Monaco Grand Prix. The Monaco was revolutionary for being the first automatic as well as the first square cased chronograph. The Hollywood film star Steve McQueen used the watch to accessorize his character in the 1971 film Le Mans. In the decades after his death the use of film stills has made the watch synonymous with McQueen. Although it was discontinued in the mid-1970s, the Monaco was reissued with a new design in 1998 and was reintroduced again with an entirely new mechanisms in 2003 in response to McQueens increasing popularity", value: 3000, image: "https://calibre11-wpengine.netdna-ssl.com/wp-content/uploads/2015/04/TAG-Heuer-Monaco-Calibre-11-CAW211P.jpg", user_id: u2.id)

i6 = Item.create!(name: "Rolex Milgauss", description: "The Rolex Oyster Perpetual Milgauss is a wristwatch model introduced by Rolex in 1956 with model number 6541. The Milgauss was designed as an antimagnetic watch specifically for those who worked in power plants, medical facilities and research labs (like CERN in Geneva)[citation needed] where electromagnetic fields can cause havoc[clarification needed] with the timing of a watch. The current (post-2007) model Milgauss is equipped with a magnetic alloy (Parachrom-Blu) hairspring[1] and movement encased by a magnetic shield, most likely[vague] composed of a high magnetic permeability material (see Mu-metal or Permalloy). The name Milgauss is derived from the Latin mille, which means one-thousand, and gauss, the unit of a magnetic field. This model is so named because it can withstand a magnetic flux density of 1,000 gauss", value: 4500, image: "https://www.bobswatches.com/images/110740-p---Copy.jpg?v=6", user_id: u2.id)

i7 = Item.create!(name: "Patek Phillipe Calatrava", description: "The Patek Philippe Calatrava is a line of dress watches built by Swiss watchmaker Patek Philippe, introduced in 1932. These watches are considered the flagship model of Patek Philippe. The first version of the Calatrava was launched in 1932, inspired by the Bauhaus principle.The most popular model in the Calatrava range was the 3919, with the guilloché Clous de Paris bezel, introduced in 1985. After 21 years, it was replaced in March 2006 by the slightly larger 5119 model.[2] This change in size reflected a growing trend for larger watches. Another famous model was the 96, whose modern incarnation is the considerably larger 5196. Some Calatravas (such as the current 5227) feature a date function, whereas others (such as the 5116, 5119, 5120, 5123, 5196) display only hours and minutes (and, in some cases, seconds). Current (2014) prices start from around US$19,000", value: 13000, image: "http://cdn2.jomashop.com/media/catalog/product/p/a/patek-philippe-calatrava-white-dial-18kt-rose-gold-mens-watch-5119r.jpg", user_id: u3.id)

i8 = Item.create!(name: "Zenith El Primero", description: "It was in 1962 that the basics of the El Primero movement first took shape on the drawing board. The idea was simple: to create an iconic watch that would be launched in time for the centenary of the Manufacture in 1965. The idea was simple, but the technical specifications were not. It was to be the first automatic chronograph ever. Better still, the caliber was to be fully integrated and designed as an inseparable whole. There would be no additional module, but instead a construction built around a column wheel and a central rotor mounted on ball bearings. It would also need to beat at a high frequency in order to be the world’s most accurate chronograph. To complicate matters still further, the movement was to be miniaturised and equipped with a date mechanism. All these factors amounted to an equation so complex that it would take seven years to solve it – four years past the anniversary date.", value: 13000, image: "https://static1.squarespace.com/static/512f9596e4b0ed945e3306aa/t/55130369e4b0cd853fcf4802/1427309419327/?format=750w", user_id: u1.id)

i9 = Item.create!(name: "Audemars Piguet Royal Oak", description: "The Royal Oak was characterized by a revolutionary design in the form of a rounded octagon. At the time, luxury watches on the market were all round, slim and in gold. Genta designed an avant garde octagonal watch in steel with sharp angles and visible screws.Priced at 3,650 Swiss francs when first launched, it was the most expensive luxury sports watch, priced ten times more than a Rolex Submariner (costing around 300 Swiss francs in circa 1973).The Royal Oak was the first high-end sports watch made of steel, recognizable by its octagonal bezel with eight hexagonal white gold screws, the guilloche engraving on its dial (known as grande tapisserie), its integrated bracelet and eight visible bolts on the back.[11][16] The watch was slim (7mm) and had a case diameter of 39mm.[11] The cost for producing the case (not including the material) of the Royal Oak in steel became much more expensive than a similar gold watch.", value: 3000, image: "https://static1.squarespace.com/static/52c8b0b3e4b0ef830a21d35b/544fb3abe4b0634e4a9b7589/55c2469fe4b0fa221028fe20/1438795433970/IMG_9242.jpg?format=500w", user_id: u3.id)

i10 = Item.create!(name: "Heuer Monaco", description: "The Heuer Monaco is a series of automatic chronograph wristwatch originally introduced by Heuer in 1969 in honour of the Monaco Grand Prix. The Monaco was revolutionary for being the first automatic as well as the first square cased chronograph. The Hollywood film star Steve McQueen used the watch to accessorize his character in the 1971 film Le Mans. In the decades after his death the use of film stills has made the watch synonymous with McQueen. Although it was discontinued in the mid-1970s, the Monaco was reissued with a new design in 1998 and was reintroduced again with an entirely new mechanisms in 2003 in response to McQueens increasing popularity", value: 3000, image: "https://calibre11-wpengine.netdna-ssl.com/wp-content/uploads/2015/04/TAG-Heuer-Monaco-Calibre-11-CAW211P.jpg", user_id: u2.id)
